
services:
  # Mongodb service
  mongo_db:
    container_name: mongo_db
    image: mongo:7.0.7
    restart: always
    volumes:
      - mongo_data:/data/db
    ports:
      - 27017:27017

  # Node api service
  api:
    build: .
    ports:
      # local->container
      - 5000:5000
    environment:
      PORT: 5000
      MONGODB_URI: mongodb://mongo_db:27017
      DB_NAME: songs
    depends_on: 
      - mongo_db

volumes:
  mongo_data: {}
